name: breeze

services:
  redis:
    container_name: redis
    image: redis:7.4.0-alpine
    restart: always
    networks:
      - redisnet
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  postgres:
    container_name: postgres
    image: postgres:16.4-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: breeze
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  asynqmon:
    container_name: asynqmon
    image: hibiken/asynqmon
    restart: always
    networks:
      - redisnet
    ports:
      - "8080:8080"
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis

networks:
  redisnet:

volumes:
  pg_data:
