// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: dummy.sql

package db

import (
	"context"
)

const dummy = `-- name: Dummy :one
SELECT 'Hello World'
`

func (q *Queries) Dummy(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, dummy)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}
